# °€{¢×®[|[{€ ₥€₭ⱠⱫ₴
# ░▒▓█ ₥€₭ⱠⱫ₴ ¢Ⱨ₳Ø₴ █▓▒░

# ₦Ø₮₳₵Ɉⱥ ₴Ɏ₴₮€₥
resetAtFixedTime: true
fixedTime: "04:00"
windowHours: 24

# ₴Ƶ¥฿₭ł€ Ø₮₩ł€Ɽ₳₦ł€
quickOpen: true

# ĐŹ₩ł€₭ł
sounds:
  noKey: ENTITY_VILLAGER_NO
  spin: UI_BUTTON_CLICK
  win: ENTITY_PLAYER_LEVELUP

# ₳₦Ø₦₴Ɏ ₥€₭ⱠⱫ₴
broadcast:
  enabled: true
  messages:
    win: "{player} wygrał {item} x{amount} z {case}"
    top: "{player} pobił TOP DROP! {item} x{amount}"
    rotation: "Nowy dzień! Dziś wysoka szansa na {boost_item}"

# ĦØⱠØ₲Ɽ₳₥ ₳₦ł₥₳₵ɾ€
holograms:
  enabled: true
  animations:
    enabled: true
    updateInterval: 10
    effects:
      rainbow: true
      particles: true
      fire: true
      glitch: true
      neon: true
      constellation: true
      digitalRain: true
      pulsingBorder: true
      waveAnimation: true

# ₥€₭ⱠⱫ₴ ł₦₣Ø
version: 1.0.0
author: meklas